version: "3.4"

services:
  api:
    container_name: api_dev
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    command: npm run start:debug
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass123"
      POSTGRES_DB: "hometask-3"